version: "3"

services:
  app:
    container_name: ota_tracker
    restart: always
    build:
      context: .
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app
    environment:
      - DB_NAME=ota_tracker
      - DB_USER=s3-infosoft
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8001"
  db:
    restart: always
    image: postgres:11.4-alpine
    container_name: tracker_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=s3-infosoft
      - POSTGRES_DB=ota_tracker
volumes:
  postgres_data: