version: "3"

services:
  app:
    container_name: ota_tracker
    restart: always
    build:
      context: .
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app
    environment:
      - DB_NAME=ota_tracker
      - DB_USER=s3-infosoft
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
#      - db
      - elasticsearch
      - logstash
      - kibana
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
#  db:
#    restart: always
#    image: postgres:11.4-alpine
#    container_name: tracker_db
#    ports:
#      - "5433:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=s3-infosoft
#      - POSTGRES_DB=ota_tracker
  elasticsearch:
    restart: always
    container_name: elasticsearch
    image: elasticsearch:7.2.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk

  logstash:
    restart: always
    container_name: logstash
    image: logstash:7.2.0
    ports:
      - "5001:5000"
      - "9600:9600"
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./app/logs:/usr/share/logstash/logs
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  kibana:
    restart: always
    container_name: kibana
    image: kibana:7.2.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - elk

networks:

  elk:
    driver: bridge

#volumes:
#  postgres_data: